### ISSUE TITLE
Term show page throws error when Deprecated value exists as URI

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#575]
**Describe the bug**
After deprecating (and reviewing) a Term and adding the replacing URI, the Term page then shows the "We're sorry, something went wrong" error.

Error message in logs:
```
F, [2019-12-18T11:32:00.461735 #52508] FATAL -- : 
ActionView::Template::Error (undefined method `active_triples_resources_path' for #<#<Class:0x00007f2a494262e0>:0x00007f29e2efe990>):
     8:     <div class="alert alert-warning">
     9:       <strong>Deprecated</strong> -
    10:       <%= :is_replaced_by.to_s.humanize %>
    11:       <%= link_to @term.get_values(:is_replaced_by).first, @term.get_values(:is_replaced_by).first %>
    12:     </div>
    13: <% end %>
    14: 
  app/views/terms/show.html.erb:11:in `_app_views_terms_show_html_erb___3736061735529446676_69909797339220'
  app/controllers/terms_controller.rb:21:in `show'
  lib/conneg_middleware.rb:11:in `call'
```

I believe the recent changes to ensure URIs are being saved correctly are working as expected and we just missed this update to the view. All existing is_replaced_by values are still strings and they were displaying ok.

**To Reproduce**
1. Edit an existing Term, click Deprecate
2. Fill in a URI value on the Deprecate Form
3. Review the Term
4. Visit the Term show page, see "We're sorry, something went wrong."

**Expected behavior**
When a Term is deprecated, the term show page shows the Term values along with a Deprecated message and the optional new URI.

**Comment by wickr** [comment]
Closed by #575
